/*
 * This file is generated by jOOQ.
 */
package com.colak.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Persons implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long personKey;
    private String name;

    public Persons() {}

    public Persons(Persons value) {
        this.personKey = value.personKey;
        this.name = value.name;
    }

    public Persons(
        Long personKey,
        String name
    ) {
        this.personKey = personKey;
        this.name = name;
    }

    /**
     * Getter for <code>userdb.persons.person_key</code>.
     */
    public Long getPersonKey() {
        return this.personKey;
    }

    /**
     * Setter for <code>userdb.persons.person_key</code>.
     */
    public void setPersonKey(Long personKey) {
        this.personKey = personKey;
    }

    /**
     * Getter for <code>userdb.persons.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>userdb.persons.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Persons other = (Persons) obj;
        if (this.personKey == null) {
            if (other.personKey != null)
                return false;
        }
        else if (!this.personKey.equals(other.personKey))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.personKey == null) ? 0 : this.personKey.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Persons (");

        sb.append(personKey);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
