/*
 * This file is generated by jOOQ.
 */
package com.colak.db.tables.records;


import com.colak.db.tables.Persons;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PersonsRecord extends UpdatableRecordImpl<PersonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>userdb.persons.person_key</code>.
     */
    public void setPersonKey(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>userdb.persons.person_key</code>.
     */
    public Long getPersonKey() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>userdb.persons.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>userdb.persons.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonsRecord
     */
    public PersonsRecord() {
        super(Persons.PERSONS);
    }

    /**
     * Create a detached, initialised PersonsRecord
     */
    public PersonsRecord(Long personKey, String name) {
        super(Persons.PERSONS);

        setPersonKey(personKey);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PersonsRecord
     */
    public PersonsRecord(com.colak.db.tables.pojos.Persons value) {
        super(Persons.PERSONS);

        if (value != null) {
            setPersonKey(value.getPersonKey());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
