/*
 * This file is generated by jOOQ.
 */
package com.colak.db;


import com.colak.db.tables.Persons;


/**
 * Convenience access to all tables in userdb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>userdb.persons</code>.
     */
    public static final Persons PERSONS = Persons.PERSONS;
}
