/*
 * This file is generated by jOOQ.
 */
package com.colak.db;


import com.colak.db.tables.Persons;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Userdb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>userdb</code>
     */
    public static final Userdb USERDB = new Userdb();

    /**
     * The table <code>userdb.persons</code>.
     */
    public final Persons PERSONS = Persons.PERSONS;

    /**
     * No further instances allowed
     */
    private Userdb() {
        super("userdb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Persons.PERSONS
        );
    }
}
